# Generated by Django 4.1.4 on 2022-12-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='plan',
            field=models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('+Advanced', '+Advanced'), ('+Premuim', '+Premuim'), ('+Ultimate', '+Ultimate'), ('+Spartan', '+Spartan')], default='Make a deposit to get started', max_length=50),
        ),
    ]
